name: Sync Fork from Upstream
on:
  schedule:
    - cron: '0 18 * * 5'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          base: main
          head: main
